spring:
  datasource:
    #username: root
    #url: jdbc:mysql://127.0.0.1:3306/advanced_jpa
    url: jdbc:mysql://azdb-mysql-02.mysql.database.azure.com:3306/advanced_jpa
    username: sri96
    password: AzureSql@2024
    ssl-mode: require
    #password: ParkView0502

logging:
  level:
    org:
      hibernate:
        SQL: TRACE
        orm:
          jdbc:
            bind: TRACE